services:
  # A Docker web service
  - type: web
    name: intent-classification-evaluation-ui
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: ustreamlit run Home.py
